package org.noMoon.ArtificalSociety.history.DO;

import java.util.Date;

public class History {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.ID
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.GMT_CREATE
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.GMT_MODIFIED
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.SOCIETY_ID
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    private String societyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.PERSON_ID
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    private String personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.TYPE
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HISTORY_LIST
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    private String historyList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.ID
     *
     * @return the value of HISTORY.ID
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.ID
     *
     * @param id the value for HISTORY.ID
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.GMT_CREATE
     *
     * @return the value of HISTORY.GMT_CREATE
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.GMT_CREATE
     *
     * @param gmtCreate the value for HISTORY.GMT_CREATE
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.GMT_MODIFIED
     *
     * @return the value of HISTORY.GMT_MODIFIED
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.GMT_MODIFIED
     *
     * @param gmtModified the value for HISTORY.GMT_MODIFIED
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.SOCIETY_ID
     *
     * @return the value of HISTORY.SOCIETY_ID
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    public String getSocietyId() {
        return societyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.SOCIETY_ID
     *
     * @param societyId the value for HISTORY.SOCIETY_ID
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    public void setSocietyId(String societyId) {
        this.societyId = societyId == null ? null : societyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.PERSON_ID
     *
     * @return the value of HISTORY.PERSON_ID
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.PERSON_ID
     *
     * @param personId the value for HISTORY.PERSON_ID
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    public void setPersonId(String personId) {
        this.personId = personId == null ? null : personId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.TYPE
     *
     * @return the value of HISTORY.TYPE
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.TYPE
     *
     * @param type the value for HISTORY.TYPE
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HISTORY_LIST
     *
     * @return the value of HISTORY.HISTORY_LIST
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    public String getHistoryList() {
        return historyList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HISTORY_LIST
     *
     * @param historyList the value for HISTORY.HISTORY_LIST
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    public void setHistoryList(String historyList) {
        this.historyList = historyList == null ? null : historyList.trim();
    }
}