package org.noMoon.ArtificalSociety.commons.DO;

public class Sequence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCES.ID
     *
     * @mbggenerated Fri Aug 21 02:57:35 EDT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCES.SEQUENCE_NAME
     *
     * @mbggenerated Fri Aug 21 02:57:35 EDT 2015
     */
    private String sequenceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SEQUENCES.SEQUENCE_VALUE
     *
     * @mbggenerated Fri Aug 21 02:57:35 EDT 2015
     */
    private Integer sequenceValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCES.ID
     *
     * @return the value of SEQUENCES.ID
     *
     * @mbggenerated Fri Aug 21 02:57:35 EDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCES.ID
     *
     * @param id the value for SEQUENCES.ID
     *
     * @mbggenerated Fri Aug 21 02:57:35 EDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCES.SEQUENCE_NAME
     *
     * @return the value of SEQUENCES.SEQUENCE_NAME
     *
     * @mbggenerated Fri Aug 21 02:57:35 EDT 2015
     */
    public String getSequenceName() {
        return sequenceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCES.SEQUENCE_NAME
     *
     * @param sequenceName the value for SEQUENCES.SEQUENCE_NAME
     *
     * @mbggenerated Fri Aug 21 02:57:35 EDT 2015
     */
    public void setSequenceName(String sequenceName) {
        this.sequenceName = sequenceName == null ? null : sequenceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SEQUENCES.SEQUENCE_VALUE
     *
     * @return the value of SEQUENCES.SEQUENCE_VALUE
     *
     * @mbggenerated Fri Aug 21 02:57:35 EDT 2015
     */
    public Integer getSequenceValue() {
        return sequenceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SEQUENCES.SEQUENCE_VALUE
     *
     * @param sequenceValue the value for SEQUENCES.SEQUENCE_VALUE
     *
     * @mbggenerated Fri Aug 21 02:57:35 EDT 2015
     */
    public void setSequenceValue(Integer sequenceValue) {
        this.sequenceValue = sequenceValue;
    }
}