package org.noMoon.ArtificalSociety.history.DAO;

import org.noMoon.ArtificalSociety.history.DO.History;

public interface HistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    int insert(History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    int insertSelective(History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    History selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    int updateByPrimaryKeySelective(History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    int updateByPrimaryKeyWithBLOBs(History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbggenerated Fri Oct 16 03:38:52 EDT 2015
     */
    int updateByPrimaryKey(History record);
}