package org.noMoon.ArtificalSociety.society.DAO;

import org.noMoon.ArtificalSociety.society.DO.Society;

public interface SocietyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOCIETY
     *
     * @mbggenerated Fri Aug 21 02:57:35 EDT 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOCIETY
     *
     * @mbggenerated Fri Aug 21 02:57:35 EDT 2015
     */
    int insert(Society record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOCIETY
     *
     * @mbggenerated Fri Aug 21 02:57:35 EDT 2015
     */
    int insertSelective(Society record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOCIETY
     *
     * @mbggenerated Fri Aug 21 02:57:35 EDT 2015
     */
    Society selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOCIETY
     *
     * @mbggenerated Fri Aug 21 02:57:35 EDT 2015
     */
    int updateByPrimaryKeySelective(Society record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOCIETY
     *
     * @mbggenerated Fri Aug 21 02:57:35 EDT 2015
     */
    int updateByPrimaryKey(Society record);
}