package org.noMoon.ArtificalSociety.institution.DO;

import java.util.Date;

public class Club {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLUB.ID
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLUB.GMT_CREATE
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLUB.GMT_MODIFIED
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLUB.SOCIETY_ID
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    private String societyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLUB.TITLE
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLUB.TYPE
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLUB.CITY
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLUB.POPULATION
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    private Integer population;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLUB.STARTING_YEAR
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    private Integer startingYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLUB.ENDING_YEAR
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    private Integer endingYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLUB.TRAIT
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    private String trait;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLUB.ID
     *
     * @return the value of CLUB.ID
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLUB.ID
     *
     * @param id the value for CLUB.ID
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLUB.GMT_CREATE
     *
     * @return the value of CLUB.GMT_CREATE
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLUB.GMT_CREATE
     *
     * @param gmtCreate the value for CLUB.GMT_CREATE
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLUB.GMT_MODIFIED
     *
     * @return the value of CLUB.GMT_MODIFIED
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLUB.GMT_MODIFIED
     *
     * @param gmtModified the value for CLUB.GMT_MODIFIED
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLUB.SOCIETY_ID
     *
     * @return the value of CLUB.SOCIETY_ID
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public String getSocietyId() {
        return societyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLUB.SOCIETY_ID
     *
     * @param societyId the value for CLUB.SOCIETY_ID
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public void setSocietyId(String societyId) {
        this.societyId = societyId == null ? null : societyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLUB.TITLE
     *
     * @return the value of CLUB.TITLE
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLUB.TITLE
     *
     * @param title the value for CLUB.TITLE
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLUB.TYPE
     *
     * @return the value of CLUB.TYPE
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLUB.TYPE
     *
     * @param type the value for CLUB.TYPE
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLUB.CITY
     *
     * @return the value of CLUB.CITY
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLUB.CITY
     *
     * @param city the value for CLUB.CITY
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLUB.POPULATION
     *
     * @return the value of CLUB.POPULATION
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public Integer getPopulation() {
        return population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLUB.POPULATION
     *
     * @param population the value for CLUB.POPULATION
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public void setPopulation(Integer population) {
        this.population = population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLUB.STARTING_YEAR
     *
     * @return the value of CLUB.STARTING_YEAR
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public Integer getStartingYear() {
        return startingYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLUB.STARTING_YEAR
     *
     * @param startingYear the value for CLUB.STARTING_YEAR
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public void setStartingYear(Integer startingYear) {
        this.startingYear = startingYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLUB.ENDING_YEAR
     *
     * @return the value of CLUB.ENDING_YEAR
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public Integer getEndingYear() {
        return endingYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLUB.ENDING_YEAR
     *
     * @param endingYear the value for CLUB.ENDING_YEAR
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public void setEndingYear(Integer endingYear) {
        this.endingYear = endingYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLUB.TRAIT
     *
     * @return the value of CLUB.TRAIT
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public String getTrait() {
        return trait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLUB.TRAIT
     *
     * @param trait the value for CLUB.TRAIT
     *
     * @mbggenerated Fri Sep 04 21:56:34 EDT 2015
     */
    public void setTrait(String trait) {
        this.trait = trait == null ? null : trait.trim();
    }
}