package org.noMoon.ArtificalSociety.institution.DO;

import org.noMoon.ArtificalSociety.institution.enums.InstitutionEnum;

import java.util.Date;

public class Institution {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.ID
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.GMT_CREATE
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.GMT_MODIFIED
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.INSTITUTION_TYPE
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    private InstitutionEnum institutionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.SOCIETY_ID
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    private String societyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.TITLE
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.TYPE
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.CITY
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.POPULATION
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    private Integer population;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.STARTING_YEAR
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    private Integer startingYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INSTITUTION.ENDING_YEAR
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    private Integer endingYear;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.ID
     *
     * @return the value of INSTITUTION.ID
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.ID
     *
     * @param id the value for INSTITUTION.ID
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.GMT_CREATE
     *
     * @return the value of INSTITUTION.GMT_CREATE
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.GMT_CREATE
     *
     * @param gmtCreate the value for INSTITUTION.GMT_CREATE
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.GMT_MODIFIED
     *
     * @return the value of INSTITUTION.GMT_MODIFIED
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.GMT_MODIFIED
     *
     * @param gmtModified the value for INSTITUTION.GMT_MODIFIED
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.INSTITUTION_TYPE
     *
     * @return the value of INSTITUTION.INSTITUTION_TYPE
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public InstitutionEnum getInstitutionType() {
        return institutionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.INSTITUTION_TYPE
     *
     * @param institutionType the value for INSTITUTION.INSTITUTION_TYPE
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public void setInstitutionType(InstitutionEnum institutionType) {
        this.institutionType = institutionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.SOCIETY_ID
     *
     * @return the value of INSTITUTION.SOCIETY_ID
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public String getSocietyId() {
        return societyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.SOCIETY_ID
     *
     * @param societyId the value for INSTITUTION.SOCIETY_ID
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public void setSocietyId(String societyId) {
        this.societyId = societyId == null ? null : societyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.TITLE
     *
     * @return the value of INSTITUTION.TITLE
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.TITLE
     *
     * @param title the value for INSTITUTION.TITLE
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.TYPE
     *
     * @return the value of INSTITUTION.TYPE
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.TYPE
     *
     * @param type the value for INSTITUTION.TYPE
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.CITY
     *
     * @return the value of INSTITUTION.CITY
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.CITY
     *
     * @param city the value for INSTITUTION.CITY
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.POPULATION
     *
     * @return the value of INSTITUTION.POPULATION
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public Integer getPopulation() {
        return population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.POPULATION
     *
     * @param population the value for INSTITUTION.POPULATION
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public void setPopulation(Integer population) {
        this.population = population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.STARTING_YEAR
     *
     * @return the value of INSTITUTION.STARTING_YEAR
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public Integer getStartingYear() {
        return startingYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.STARTING_YEAR
     *
     * @param startingYear the value for INSTITUTION.STARTING_YEAR
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public void setStartingYear(Integer startingYear) {
        this.startingYear = startingYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INSTITUTION.ENDING_YEAR
     *
     * @return the value of INSTITUTION.ENDING_YEAR
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public Integer getEndingYear() {
        return endingYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INSTITUTION.ENDING_YEAR
     *
     * @param endingYear the value for INSTITUTION.ENDING_YEAR
     *
     * @mbggenerated Wed Sep 02 00:15:00 EDT 2015
     */
    public void setEndingYear(Integer endingYear) {
        this.endingYear = endingYear;
    }
}