package org.noMoon.ArtificalSociety.group.DO;

import java.util.Date;

public class Group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AS_GROUP.ID
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AS_GROUP.GMT_CREATE
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AS_GROUP.GMT_MODIFIED
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AS_GROUP.SOCIETY_ID
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    private String societyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AS_GROUP.GROUP_LABEL
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    private String groupLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AS_GROUP.GROUP_YEAR
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    private Integer groupYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AS_GROUP.MEMBER_LIST
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    private String memberList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AS_GROUP.ID
     *
     * @return the value of AS_GROUP.ID
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AS_GROUP.ID
     *
     * @param id the value for AS_GROUP.ID
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AS_GROUP.GMT_CREATE
     *
     * @return the value of AS_GROUP.GMT_CREATE
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AS_GROUP.GMT_CREATE
     *
     * @param gmtCreate the value for AS_GROUP.GMT_CREATE
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AS_GROUP.GMT_MODIFIED
     *
     * @return the value of AS_GROUP.GMT_MODIFIED
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AS_GROUP.GMT_MODIFIED
     *
     * @param gmtModified the value for AS_GROUP.GMT_MODIFIED
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AS_GROUP.SOCIETY_ID
     *
     * @return the value of AS_GROUP.SOCIETY_ID
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    public String getSocietyId() {
        return societyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AS_GROUP.SOCIETY_ID
     *
     * @param societyId the value for AS_GROUP.SOCIETY_ID
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    public void setSocietyId(String societyId) {
        this.societyId = societyId == null ? null : societyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AS_GROUP.GROUP_LABEL
     *
     * @return the value of AS_GROUP.GROUP_LABEL
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    public String getGroupLabel() {
        return groupLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AS_GROUP.GROUP_LABEL
     *
     * @param groupLabel the value for AS_GROUP.GROUP_LABEL
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    public void setGroupLabel(String groupLabel) {
        this.groupLabel = groupLabel == null ? null : groupLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AS_GROUP.GROUP_YEAR
     *
     * @return the value of AS_GROUP.GROUP_YEAR
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    public Integer getGroupYear() {
        return groupYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AS_GROUP.GROUP_YEAR
     *
     * @param groupYear the value for AS_GROUP.GROUP_YEAR
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    public void setGroupYear(Integer groupYear) {
        this.groupYear = groupYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AS_GROUP.MEMBER_LIST
     *
     * @return the value of AS_GROUP.MEMBER_LIST
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    public String getMemberList() {
        return memberList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AS_GROUP.MEMBER_LIST
     *
     * @param memberList the value for AS_GROUP.MEMBER_LIST
     *
     * @mbggenerated Sat Oct 10 22:45:10 EDT 2015
     */
    public void setMemberList(String memberList) {
        this.memberList = memberList == null ? null : memberList.trim();
    }
}