package org.noMoon.ArtificalSociety.person.DO;

import org.noMoon.ArtificalSociety.person.Enums.FriendshipTypeEnum;

import java.util.Date;

public class Friendship {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIENDSHIP.ID
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIENDSHIP.GMT_CREATE
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIENDSHIP.GMT_MODIFIED
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIENDSHIP.SOCIETY_ID
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    private String societyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIENDSHIP.PERSON_A_ID
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    private String personAId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIENDSHIP.PERSON_B_ID
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    private String personBId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIENDSHIP.FRIEND_TYPE
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    private FriendshipTypeEnum friendType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIENDSHIP.IS_FRIEND
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    private Boolean isFriend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIENDSHIP.STRENGTH
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    private Double strength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIENDSHIP.PROBABILITY
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    private Double probability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIENDSHIP.ROLE
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FRIENDSHIP.DESCRIPTION
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    private String description;

    public Friendship(String societyId,String personAId,String personBId, FriendshipTypeEnum friendType, double strength){
        this.setSocietyId(societyId);
        this.setPersonAId(personAId);
        this.setPersonBId(personBId);
        this.setFriendType(friendType);
        this.setStrength(strength);
        this.setIsFriend(true);
    }

    public Friendship(String societyId,String personAId,String personBId, FriendshipTypeEnum friendType, double strength, String desc){
        this.setSocietyId(societyId);
        this.setPersonAId(personAId);
        this.setPersonBId(personBId);
        this.setFriendType(friendType);
        this.setStrength(strength);
        this.setDescription(desc);
        this.setIsFriend(true);
    }

    public Friendship(){}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIENDSHIP.ID
     *
     * @return the value of FRIENDSHIP.ID
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIENDSHIP.ID
     *
     * @param id the value for FRIENDSHIP.ID
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIENDSHIP.GMT_CREATE
     *
     * @return the value of FRIENDSHIP.GMT_CREATE
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIENDSHIP.GMT_CREATE
     *
     * @param gmtCreate the value for FRIENDSHIP.GMT_CREATE
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIENDSHIP.GMT_MODIFIED
     *
     * @return the value of FRIENDSHIP.GMT_MODIFIED
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIENDSHIP.GMT_MODIFIED
     *
     * @param gmtModified the value for FRIENDSHIP.GMT_MODIFIED
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIENDSHIP.SOCIETY_ID
     *
     * @return the value of FRIENDSHIP.SOCIETY_ID
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public String getSocietyId() {
        return societyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIENDSHIP.SOCIETY_ID
     *
     * @param societyId the value for FRIENDSHIP.SOCIETY_ID
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public void setSocietyId(String societyId) {
        this.societyId = societyId == null ? null : societyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIENDSHIP.PERSON_A_ID
     *
     * @return the value of FRIENDSHIP.PERSON_A_ID
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public String getPersonAId() {
        return personAId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIENDSHIP.PERSON_A_ID
     *
     * @param personAId the value for FRIENDSHIP.PERSON_A_ID
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public void setPersonAId(String personAId) {
        this.personAId = personAId == null ? null : personAId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIENDSHIP.PERSON_B_ID
     *
     * @return the value of FRIENDSHIP.PERSON_B_ID
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public String getPersonBId() {
        return personBId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIENDSHIP.PERSON_B_ID
     *
     * @param personBId the value for FRIENDSHIP.PERSON_B_ID
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public void setPersonBId(String personBId) {
        this.personBId = personBId == null ? null : personBId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIENDSHIP.FRIEND_TYPE
     *
     * @return the value of FRIENDSHIP.FRIEND_TYPE
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public FriendshipTypeEnum getFriendType() {
        return friendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIENDSHIP.FRIEND_TYPE
     *
     * @param friendType the value for FRIENDSHIP.FRIEND_TYPE
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public void setFriendType(FriendshipTypeEnum friendType) {
        this.friendType = friendType ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIENDSHIP.IS_FRIEND
     *
     * @return the value of FRIENDSHIP.IS_FRIEND
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public Boolean getIsFriend() {
        return isFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIENDSHIP.IS_FRIEND
     *
     * @param isFriend the value for FRIENDSHIP.IS_FRIEND
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public void setIsFriend(Boolean isFriend) {
        this.isFriend = isFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIENDSHIP.STRENGTH
     *
     * @return the value of FRIENDSHIP.STRENGTH
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public Double getStrength() {
        return strength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIENDSHIP.STRENGTH
     *
     * @param strength the value for FRIENDSHIP.STRENGTH
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public void setStrength(Double strength) {
        this.strength = strength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIENDSHIP.PROBABILITY
     *
     * @return the value of FRIENDSHIP.PROBABILITY
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public Double getProbability() {
        return probability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIENDSHIP.PROBABILITY
     *
     * @param probability the value for FRIENDSHIP.PROBABILITY
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public void setProbability(Double probability) {
        this.probability = probability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIENDSHIP.ROLE
     *
     * @return the value of FRIENDSHIP.ROLE
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIENDSHIP.ROLE
     *
     * @param role the value for FRIENDSHIP.ROLE
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRIENDSHIP.DESCRIPTION
     *
     * @return the value of FRIENDSHIP.DESCRIPTION
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRIENDSHIP.DESCRIPTION
     *
     * @param description the value for FRIENDSHIP.DESCRIPTION
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}