package org.noMoon.ArtificalSociety.person.DO;

import java.util.Date;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.GMT_CREATE
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.GMT_MODIFIED
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.SOCIETY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String societyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.SEX
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.AGE
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.BIRTH_YEAR
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Integer birthYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.EXP_DEATH_YEAR
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Integer expDeathYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.RACE_INDEX
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Integer raceIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.INTELLIGENCE
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Double intelligence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.ATHLETICISM
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Double athleticism;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.RELIGION_INDEX
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Integer religionIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.NATIONALITY
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.TEMPLE_ATTENDING
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String templeAttending;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.INTEREST
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.INTEREST_WEIGHT
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String interestWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.RELATIONSHIP_STATUS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String relationshipStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.PARTNER_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String partnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.INTEREST_SIMILARITY
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Double interestSimilarity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.RELATIONSHIP_STRENGTH
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Double relationshipStrength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.RELATIONSHIP_START_YEAR
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Integer relationshipStartYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.PERSONALITY
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String personality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.CAREER_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Long careerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.CURRENT_POSITION
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String currentPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.INCOME
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Integer income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.EDUCATION
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.EDUCATION_PS_YEAR
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Integer educationPsYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.IS_IN_SCHOOL
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Boolean isInSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.YEAR_STARTED_PS_SCHOOL
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Integer yearStartedPsSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.YEAR_FINISHED_PS_SCHOOL
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Integer yearFinishedPsSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.HOMETOWN_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Long hometownHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.SCHOOL_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Long schoolHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.WORK_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Long workHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.SOC_HOMETOWN_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Long socHometownHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.SOC_SCHOOL_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Long socSchoolHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.SOC_WORK_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Long socWorkHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.FAMILY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private Long familyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.PARENT_IDS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String parentIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.CHILDREN_IDS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String childrenIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.SIBLINGS_IDS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String siblingsIds;

    private Boolean isAlive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.ID
     *
     * @return the value of PERSON.ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.ID
     *
     * @param id the value for PERSON.ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.GMT_CREATE
     *
     * @return the value of PERSON.GMT_CREATE
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.GMT_CREATE
     *
     * @param gmtCreate the value for PERSON.GMT_CREATE
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.GMT_MODIFIED
     *
     * @return the value of PERSON.GMT_MODIFIED
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.GMT_MODIFIED
     *
     * @param gmtModified the value for PERSON.GMT_MODIFIED
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.SOCIETY_ID
     *
     * @return the value of PERSON.SOCIETY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getSocietyId() {
        return societyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.SOCIETY_ID
     *
     * @param societyId the value for PERSON.SOCIETY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setSocietyId(String societyId) {
        this.societyId = societyId == null ? null : societyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.SEX
     *
     * @return the value of PERSON.SEX
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.SEX
     *
     * @param sex the value for PERSON.SEX
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.AGE
     *
     * @return the value of PERSON.AGE
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.AGE
     *
     * @param age the value for PERSON.AGE
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.BIRTH_YEAR
     *
     * @return the value of PERSON.BIRTH_YEAR
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Integer getBirthYear() {
        return birthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.BIRTH_YEAR
     *
     * @param birthYear the value for PERSON.BIRTH_YEAR
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setBirthYear(Integer birthYear) {
        this.birthYear = birthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.EXP_DEATH_YEAR
     *
     * @return the value of PERSON.EXP_DEATH_YEAR
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Integer getExpDeathYear() {
        return expDeathYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.EXP_DEATH_YEAR
     *
     * @param expDeathYear the value for PERSON.EXP_DEATH_YEAR
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setExpDeathYear(Integer expDeathYear) {
        this.expDeathYear = expDeathYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.RACE_INDEX
     *
     * @return the value of PERSON.RACE_INDEX
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Integer getRaceIndex() {
        return raceIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.RACE_INDEX
     *
     * @param raceIndex the value for PERSON.RACE_INDEX
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setRaceIndex(Integer raceIndex) {
        this.raceIndex = raceIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.INTELLIGENCE
     *
     * @return the value of PERSON.INTELLIGENCE
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Double getIntelligence() {
        return intelligence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.INTELLIGENCE
     *
     * @param intelligence the value for PERSON.INTELLIGENCE
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setIntelligence(Double intelligence) {
        this.intelligence = intelligence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.ATHLETICISM
     *
     * @return the value of PERSON.ATHLETICISM
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Double getAthleticism() {
        return athleticism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.ATHLETICISM
     *
     * @param athleticism the value for PERSON.ATHLETICISM
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setAthleticism(Double athleticism) {
        this.athleticism = athleticism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.RELIGION_INDEX
     *
     * @return the value of PERSON.RELIGION_INDEX
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Integer getReligionIndex() {
        return religionIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.RELIGION_INDEX
     *
     * @param religionIndex the value for PERSON.RELIGION_INDEX
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setReligionIndex(Integer religionIndex) {
        this.religionIndex = religionIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.NATIONALITY
     *
     * @return the value of PERSON.NATIONALITY
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.NATIONALITY
     *
     * @param nationality the value for PERSON.NATIONALITY
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.TEMPLE_ATTENDING
     *
     * @return the value of PERSON.TEMPLE_ATTENDING
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getTempleAttending() {
        return templeAttending;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.TEMPLE_ATTENDING
     *
     * @param templeAttending the value for PERSON.TEMPLE_ATTENDING
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setTempleAttending(String templeAttending) {
        this.templeAttending = templeAttending == null ? null : templeAttending.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.INTEREST
     *
     * @return the value of PERSON.INTEREST
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.INTEREST
     *
     * @param interest the value for PERSON.INTEREST
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setInterest(String interest) {
        this.interest = interest == null ? null : interest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.INTEREST_WEIGHT
     *
     * @return the value of PERSON.INTEREST_WEIGHT
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getInterestWeight() {
        return interestWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.INTEREST_WEIGHT
     *
     * @param interestWeight the value for PERSON.INTEREST_WEIGHT
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setInterestWeight(String interestWeight) {
        this.interestWeight = interestWeight == null ? null : interestWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.RELATIONSHIP_STATUS
     *
     * @return the value of PERSON.RELATIONSHIP_STATUS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getRelationshipStatus() {
        return relationshipStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.RELATIONSHIP_STATUS
     *
     * @param relationshipStatus the value for PERSON.RELATIONSHIP_STATUS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setRelationshipStatus(String relationshipStatus) {
        this.relationshipStatus = relationshipStatus == null ? null : relationshipStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.PARTNER_ID
     *
     * @return the value of PERSON.PARTNER_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.PARTNER_ID
     *
     * @param partnerId the value for PERSON.PARTNER_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId == null ? null : partnerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.INTEREST_SIMILARITY
     *
     * @return the value of PERSON.INTEREST_SIMILARITY
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Double getInterestSimilarity() {
        return interestSimilarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.INTEREST_SIMILARITY
     *
     * @param interestSimilarity the value for PERSON.INTEREST_SIMILARITY
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setInterestSimilarity(Double interestSimilarity) {
        this.interestSimilarity = interestSimilarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.RELATIONSHIP_STRENGTH
     *
     * @return the value of PERSON.RELATIONSHIP_STRENGTH
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Double getRelationshipStrength() {
        return relationshipStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.RELATIONSHIP_STRENGTH
     *
     * @param relationshipStrength the value for PERSON.RELATIONSHIP_STRENGTH
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setRelationshipStrength(Double relationshipStrength) {
        this.relationshipStrength = relationshipStrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.RELATIONSHIP_START_YEAR
     *
     * @return the value of PERSON.RELATIONSHIP_START_YEAR
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Integer getRelationshipStartYear() {
        return relationshipStartYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.RELATIONSHIP_START_YEAR
     *
     * @param relationshipStartYear the value for PERSON.RELATIONSHIP_START_YEAR
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setRelationshipStartYear(Integer relationshipStartYear) {
        this.relationshipStartYear = relationshipStartYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.PERSONALITY
     *
     * @return the value of PERSON.PERSONALITY
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getPersonality() {
        return personality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.PERSONALITY
     *
     * @param personality the value for PERSON.PERSONALITY
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setPersonality(String personality) {
        this.personality = personality == null ? null : personality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.CAREER_ID
     *
     * @return the value of PERSON.CAREER_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Long getCareerId() {
        return careerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.CAREER_ID
     *
     * @param careerId the value for PERSON.CAREER_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setCareerId(Long careerId) {
        this.careerId = careerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.CURRENT_POSITION
     *
     * @return the value of PERSON.CURRENT_POSITION
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getCurrentPosition() {
        return currentPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.CURRENT_POSITION
     *
     * @param currentPosition the value for PERSON.CURRENT_POSITION
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setCurrentPosition(String currentPosition) {
        this.currentPosition = currentPosition == null ? null : currentPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.INCOME
     *
     * @return the value of PERSON.INCOME
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Integer getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.INCOME
     *
     * @param income the value for PERSON.INCOME
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setIncome(Integer income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.EDUCATION
     *
     * @return the value of PERSON.EDUCATION
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.EDUCATION
     *
     * @param education the value for PERSON.EDUCATION
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.EDUCATION_PS_YEAR
     *
     * @return the value of PERSON.EDUCATION_PS_YEAR
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Integer getEducationPsYear() {
        return educationPsYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.EDUCATION_PS_YEAR
     *
     * @param educationPsYear the value for PERSON.EDUCATION_PS_YEAR
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setEducationPsYear(Integer educationPsYear) {
        this.educationPsYear = educationPsYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.IS_IN_SCHOOL
     *
     * @return the value of PERSON.IS_IN_SCHOOL
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Boolean getIsInSchool() {
        return isInSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.IS_IN_SCHOOL
     *
     * @param isInSchool the value for PERSON.IS_IN_SCHOOL
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setIsInSchool(Boolean isInSchool) {
        this.isInSchool = isInSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.YEAR_STARTED_PS_SCHOOL
     *
     * @return the value of PERSON.YEAR_STARTED_PS_SCHOOL
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Integer getYearStartedPsSchool() {
        return yearStartedPsSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.YEAR_STARTED_PS_SCHOOL
     *
     * @param yearStartedPsSchool the value for PERSON.YEAR_STARTED_PS_SCHOOL
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setYearStartedPsSchool(Integer yearStartedPsSchool) {
        this.yearStartedPsSchool = yearStartedPsSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.YEAR_FINISHED_PS_SCHOOL
     *
     * @return the value of PERSON.YEAR_FINISHED_PS_SCHOOL
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Integer getYearFinishedPsSchool() {
        return yearFinishedPsSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.YEAR_FINISHED_PS_SCHOOL
     *
     * @param yearFinishedPsSchool the value for PERSON.YEAR_FINISHED_PS_SCHOOL
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setYearFinishedPsSchool(Integer yearFinishedPsSchool) {
        this.yearFinishedPsSchool = yearFinishedPsSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.HOMETOWN_HISTORY_ID
     *
     * @return the value of PERSON.HOMETOWN_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Long getHometownHistoryId() {
        return hometownHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.HOMETOWN_HISTORY_ID
     *
     * @param hometownHistoryId the value for PERSON.HOMETOWN_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setHometownHistoryId(Long hometownHistoryId) {
        this.hometownHistoryId = hometownHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.SCHOOL_HISTORY_ID
     *
     * @return the value of PERSON.SCHOOL_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Long getSchoolHistoryId() {
        return schoolHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.SCHOOL_HISTORY_ID
     *
     * @param schoolHistoryId the value for PERSON.SCHOOL_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setSchoolHistoryId(Long schoolHistoryId) {
        this.schoolHistoryId = schoolHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.WORK_HISTORY_ID
     *
     * @return the value of PERSON.WORK_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Long getWorkHistoryId() {
        return workHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.WORK_HISTORY_ID
     *
     * @param workHistoryId the value for PERSON.WORK_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setWorkHistoryId(Long workHistoryId) {
        this.workHistoryId = workHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.SOC_HOMETOWN_HISTORY_ID
     *
     * @return the value of PERSON.SOC_HOMETOWN_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Long getSocHometownHistoryId() {
        return socHometownHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.SOC_HOMETOWN_HISTORY_ID
     *
     * @param socHometownHistoryId the value for PERSON.SOC_HOMETOWN_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setSocHometownHistoryId(Long socHometownHistoryId) {
        this.socHometownHistoryId = socHometownHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.SOC_SCHOOL_HISTORY_ID
     *
     * @return the value of PERSON.SOC_SCHOOL_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Long getSocSchoolHistoryId() {
        return socSchoolHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.SOC_SCHOOL_HISTORY_ID
     *
     * @param socSchoolHistoryId the value for PERSON.SOC_SCHOOL_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setSocSchoolHistoryId(Long socSchoolHistoryId) {
        this.socSchoolHistoryId = socSchoolHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.SOC_WORK_HISTORY_ID
     *
     * @return the value of PERSON.SOC_WORK_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Long getSocWorkHistoryId() {
        return socWorkHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.SOC_WORK_HISTORY_ID
     *
     * @param socWorkHistoryId the value for PERSON.SOC_WORK_HISTORY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setSocWorkHistoryId(Long socWorkHistoryId) {
        this.socWorkHistoryId = socWorkHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.FAMILY_ID
     *
     * @return the value of PERSON.FAMILY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public Long getFamilyId() {
        return familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.FAMILY_ID
     *
     * @param familyId the value for PERSON.FAMILY_ID
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setFamilyId(Long familyId) {
        this.familyId = familyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.PARENT_IDS
     *
     * @return the value of PERSON.PARENT_IDS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.PARENT_IDS
     *
     * @param parentIds the value for PERSON.PARENT_IDS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds == null ? null : parentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.CHILDREN_IDS
     *
     * @return the value of PERSON.CHILDREN_IDS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getChildrenIds() {
        return childrenIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.CHILDREN_IDS
     *
     * @param childrenIds the value for PERSON.CHILDREN_IDS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setChildrenIds(String childrenIds) {
        this.childrenIds = childrenIds == null ? null : childrenIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.SIBLINGS_IDS
     *
     * @return the value of PERSON.SIBLINGS_IDS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getSiblingsIds() {
        return siblingsIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.SIBLINGS_IDS
     *
     * @param siblingsIds the value for PERSON.SIBLINGS_IDS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setSiblingsIds(String siblingsIds) {
        this.siblingsIds = siblingsIds == null ? null : siblingsIds.trim();
    }

    public Boolean getIsAlive() {
        return isAlive;
    }

    public void setIsAlive(Boolean isAlive) {
        this.isAlive = isAlive;
    }
}