package org.noMoon.ArtificalSociety.person.DO;

public class PersonWithBLOBs extends Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.CLUB_IDS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String clubIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.GROUP_IDS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    private String groupIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.CLUB_IDS
     *
     * @return the value of PERSON.CLUB_IDS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getClubIds() {
        return clubIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.CLUB_IDS
     *
     * @param clubIds the value for PERSON.CLUB_IDS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setClubIds(String clubIds) {
        this.clubIds = clubIds == null ? null : clubIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.GROUP_IDS
     *
     * @return the value of PERSON.GROUP_IDS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public String getGroupIds() {
        return groupIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.GROUP_IDS
     *
     * @param groupIds the value for PERSON.GROUP_IDS
     *
     * @mbggenerated Sat Oct 17 04:57:19 EDT 2015
     */
    public void setGroupIds(String groupIds) {
        this.groupIds = groupIds == null ? null : groupIds.trim();
    }
}