package org.noMoon.ArtificalSociety.career.DTO;

import com.alibaba.fastjson.JSON;
import org.noMoon.ArtificalSociety.career.DO.Career;

import java.util.Date;
import java.util.HashMap;
import java.util.List;

/**
 * Created by noMoon on 2015-09-10.
 */
public class CareerDTO {
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.GMT_CREATE
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.GMT_MODIFIED
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.SOCIETY_ID
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private String societyId;

    private String careerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.TITLE
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.SALARY_MEAN
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private Double salaryMean;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.NUM_PERCNET
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private Double numPercnet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.EDUCATION
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.NUM_YEAR_POST_SECONDARY
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private Integer numYearPostSecondary;

    private Long workplaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.TRAIT
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */

    private HashMap<String,List<String>> trait;

    public HashMap<String, List<String>> getTrait() {
        return trait;
    }

    public CareerDTO(){}

    public CareerDTO(Career career){
        this.id=career.getId();
        this.gmtCreate=career.getGmtCreate();
        this.gmtModified=career.getGmtModified();
        this.societyId=career.getSocietyId();
        this.careerId=career.getCareerId();
        this.title=career.getTitle();
        this.salaryMean=career.getSalaryMean();
        this.numPercnet=career.getNumPercnet();
        this.education=career.getEducation();
        this.numYearPostSecondary=career.getNumYearPostSecondary();
        this.trait= JSON.parseObject(career.getTrait(),HashMap.class);
        this.workplaceId=career.getWorkplaceId();
    }

    public Career convertToCareerDO(){
        Career career=new Career();
        career.setId(this.getId());
        career.setTitle(this.getTitle());
        career.setSocietyId(this.getSocietyId());
        career.setCareerId(this.getCareerId());
        career.setTitle(this.getTitle());
        career.setSalaryMean(this.getSalaryMean());
        career.setNumPercnet(this.getNumPercnet());
        career.setEducation(this.getEducation());
        career.setNumYearPostSecondary(this.getNumYearPostSecondary());
        career.setTrait(JSON.toJSONString(this.getTrait()));
        career.setWorkplaceId(this.getWorkplaceId());
        return career;
    }

    public void setTrait(HashMap<String, List<String>> trait) {
        this.trait = trait;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getGmtCreate() {
        return gmtCreate;
    }

    public Date getGmtModified() {
        return gmtModified;
    }

    public String getCareerId() {
        return careerId;
    }

    public void setCareerId(String careerId) {
        this.careerId = careerId;
    }

    public String getSocietyId() {
        return societyId;
    }

    public void setSocietyId(String societyId) {
        this.societyId = societyId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Double getSalaryMean() {
        return salaryMean;
    }

    public void setSalaryMean(Double salaryMean) {
        this.salaryMean = salaryMean;
    }

    public Double getNumPercnet() {
        return numPercnet;
    }

    public void setNumPercnet(Double numPercnet) {
        this.numPercnet = numPercnet;
    }

    public String getEducation() {
        return education;
    }

    public void setEducation(String education) {
        this.education = education;
    }

    public Integer getNumYearPostSecondary() {
        return numYearPostSecondary;
    }

    public void setNumYearPostSecondary(Integer numYearPostSecondary) {
        this.numYearPostSecondary = numYearPostSecondary;
    }

    public Long getWorkplaceId() {
        return workplaceId;
    }

    public void setWorkplaceId(Long workplaceId) {
        this.workplaceId = workplaceId;
    }
}
