package org.noMoon.ArtificalSociety.friendship.DAO;

import org.noMoon.ArtificalSociety.friendship.DO.Friendship;

import java.util.List;

public interface FriendshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRIENDSHIP
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRIENDSHIP
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    int insert(Friendship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRIENDSHIP
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    int insertSelective(Friendship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRIENDSHIP
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    Friendship selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRIENDSHIP
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    int updateByPrimaryKeySelective(Friendship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FRIENDSHIP
     *
     * @mbggenerated Thu Nov 12 03:12:31 EST 2015
     */
    int updateByPrimaryKey(Friendship record);

    Friendship selectByUserId(Friendship query);

    void insertList(List<Friendship> friendshipList);

    List<Friendship> selectByUserOneId(Friendship query);
}