package org.noMoon.ArtificalSociety.career.DO;

import java.util.Date;

public class Career {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.ID
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.GMT_CREATE
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.GMT_MODIFIED
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private Date gmtModified;

    private String careerId;

    public String getCareerId() {
        return careerId;
    }

    public void setCareerId(String careerId) {
        this.careerId = careerId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.SOCIETY_ID
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private String societyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.TITLE
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.SALARY_MEAN
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private Double salaryMean;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.NUM_PERCNET
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private Double numPercnet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.EDUCATION
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.NUM_YEAR_POST_SECONDARY
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private Integer numYearPostSecondary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CAREER.TRAIT
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    private String trait;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAREER.ID
     *
     * @return the value of CAREER.ID
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAREER.ID
     *
     * @param id the value for CAREER.ID
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAREER.GMT_CREATE
     *
     * @return the value of CAREER.GMT_CREATE
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAREER.GMT_MODIFIED
     *
     * @return the value of CAREER.GMT_MODIFIED
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAREER.SOCIETY_ID
     *
     * @return the value of CAREER.SOCIETY_ID
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public String getSocietyId() {
        return societyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAREER.SOCIETY_ID
     *
     * @param societyId the value for CAREER.SOCIETY_ID
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public void setSocietyId(String societyId) {
        this.societyId = societyId == null ? null : societyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAREER.TITLE
     *
     * @return the value of CAREER.TITLE
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAREER.TITLE
     *
     * @param title the value for CAREER.TITLE
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAREER.SALARY_MEAN
     *
     * @return the value of CAREER.SALARY_MEAN
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public Double getSalaryMean() {
        return salaryMean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAREER.SALARY_MEAN
     *
     * @param salaryMean the value for CAREER.SALARY_MEAN
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public void setSalaryMean(Double salaryMean) {
        this.salaryMean = salaryMean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAREER.NUM_PERCNET
     *
     * @return the value of CAREER.NUM_PERCNET
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public Double getNumPercnet() {
        return numPercnet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAREER.NUM_PERCNET
     *
     * @param numPercnet the value for CAREER.NUM_PERCNET
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public void setNumPercnet(Double numPercnet) {
        this.numPercnet = numPercnet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAREER.EDUCATION
     *
     * @return the value of CAREER.EDUCATION
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAREER.EDUCATION
     *
     * @param education the value for CAREER.EDUCATION
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAREER.NUM_YEAR_POST_SECONDARY
     *
     * @return the value of CAREER.NUM_YEAR_POST_SECONDARY
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public Integer getNumYearPostSecondary() {
        return numYearPostSecondary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAREER.NUM_YEAR_POST_SECONDARY
     *
     * @param numYearPostSecondary the value for CAREER.NUM_YEAR_POST_SECONDARY
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public void setNumYearPostSecondary(Integer numYearPostSecondary) {
        this.numYearPostSecondary = numYearPostSecondary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CAREER.TRAIT
     *
     * @return the value of CAREER.TRAIT
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public String getTrait() {
        return trait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CAREER.TRAIT
     *
     * @param trait the value for CAREER.TRAIT
     *
     * @mbggenerated Thu Sep 10 03:30:13 EDT 2015
     */
    public void setTrait(String trait) {
        this.trait = trait == null ? null : trait.trim();
    }
}