package org.noMoon.ArtificalSociety.career.DO;

import java.util.Date;

public class Workplace {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKPLACE.ID
     *
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKPLACE.GMT_CREATE
     *
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKPLACE.GMT_MODIFIED
     *
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKPLACE.SOCIETY_ID
     *
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    private String societyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKPLACE.TITLE
     *
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKPLACE.CITY
     *
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKPLACE.CAREERS
     *
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    private String careers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKPLACE.STARTING_YEAR
     *
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    private Integer startingYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKPLACE.ENDING_YEAR
     *
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    private Integer endingYear;

    private String institutionRef;

    private String workId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKPLACE.ID
     *
     * @return the value of WORKPLACE.ID
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKPLACE.ID
     *
     * @param id the value for WORKPLACE.ID
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKPLACE.GMT_CREATE
     *
     * @return the value of WORKPLACE.GMT_CREATE
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKPLACE.GMT_MODIFIED
     *
     * @return the value of WORKPLACE.GMT_MODIFIED
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKPLACE.SOCIETY_ID
     *
     * @return the value of WORKPLACE.SOCIETY_ID
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public String getSocietyId() {
        return societyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKPLACE.SOCIETY_ID
     *
     * @param societyId the value for WORKPLACE.SOCIETY_ID
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public void setSocietyId(String societyId) {
        this.societyId = societyId == null ? null : societyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKPLACE.TITLE
     *
     * @return the value of WORKPLACE.TITLE
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKPLACE.TITLE
     *
     * @param title the value for WORKPLACE.TITLE
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKPLACE.CITY
     *
     * @return the value of WORKPLACE.CITY
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKPLACE.CITY
     *
     * @param city the value for WORKPLACE.CITY
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKPLACE.CAREERS
     *
     * @return the value of WORKPLACE.CAREERS
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public String getCareers() {
        return careers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKPLACE.CAREERS
     *
     * @param careers the value for WORKPLACE.CAREERS
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public void setCareers(String careers) {
        this.careers = careers == null ? null : careers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKPLACE.STARTING_YEAR
     *
     * @return the value of WORKPLACE.STARTING_YEAR
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public Integer getStartingYear() {
        return startingYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKPLACE.STARTING_YEAR
     *
     * @param startingYear the value for WORKPLACE.STARTING_YEAR
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public void setStartingYear(Integer startingYear) {
        this.startingYear = startingYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKPLACE.ENDING_YEAR
     *
     * @return the value of WORKPLACE.ENDING_YEAR
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public Integer getEndingYear() {
        return endingYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKPLACE.ENDING_YEAR
     *
     * @param endingYear the value for WORKPLACE.ENDING_YEAR
     * @mbggenerated Sat Sep 12 21:30:00 EDT 2015
     */
    public void setEndingYear(Integer endingYear) {
        this.endingYear = endingYear;
    }

    public String getInstitutionRef() {
        return institutionRef;
    }

    public void setInstitutionRef(String institutionRef) {
        this.institutionRef = institutionRef;
    }

    public String getWorkId() {
        return workId;
    }

    public void setWorkId(String workId) {
        this.workId = workId;
    }
}